SELECT COUNT(*) FROM Departamento;
SELECT COUNT(*) FROM Funcionario;
SELECT COUNT(*) FROM Produto;
SELECT COUNT(*) FROM Franquia;
SELECT COUNT(*) FROM Projeto;
SELECT COUNT(*) FROM Trabalha_em;
SELECT COUNT(*) FROM Dependente;
SELECT COUNT(*) FROM Venda;
SELECT COUNT(*) FROM Item_Venda;